name: Update Badges

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
  workflow_dispatch:     

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Credly Badges in README
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: debayan-senapati   
          NUMBER_LAST_BADGES: 0             
